mass update of scripts

diff --git a/setup/pacman/link-pacman-conf-file b/setup/pacman/link-pacman-conf-file
--- a/setup/pacman/link-pacman-conf-file
+++ b/setup/pacman/link-pacman-conf-file
@@ -5,7 +5,12 @@ set -euo pipefail
 source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
 check_no_args "$@"
 
+if ! is_arch && ! is_manjaro && ! is_endeavour; then
+  exit 0
+fi
+
 if ! executable_exists 'pacman'; then
+  log 'pacman executable not found'
   exit 0
 fi
 
@@ -25,8 +30,8 @@ if ! pacman-key --list-keys | grep --quiet --fixed-strings 'FBA220DFC880C036'; t
   sudo pacman-key --recv-key 'FBA220DFC880C036' --keyserver 'keyserver.ubuntu.com'
   sudo pacman-key --lsign-key 'FBA220DFC880C036'
   sudo pacman --upgrade --noconfirm \
-      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
-      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
+    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
+    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
   log 'Added Chaotic AUR keyring and mirror list'
   log 'Refreshing pacman package database'
   sudo pacman --sync --refresh
diff --git a/setup/reflector/link-reflector-conf-file b/setup/reflector/link-reflector-conf-file
--- a/setup/reflector/link-reflector-conf-file
+++ b/setup/reflector/link-reflector-conf-file
@@ -5,10 +5,12 @@ set -euo pipefail
 source "$(dirname -- "${BASH_SOURCE[0]}")/../functions.bash"
 check_no_args "$@"
 
+if ! is_arch && ! is_endeavour; then
+  exit 0
+fi
+
 if ! executable_exists 'reflector'; then
-  if is_arch; then
-    log 'reflector executable not found'
-  fi
+  log 'reflector executable not found'
   exit 0
 fi
 
