namespace functions

diff --git a/main/sync-appimages b/main/sync-appimages
--- a/main/sync-appimages
+++ b/main/sync-appimages
@@ -5,40 +5,40 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
+log::enable_err_trap
+system::require_bash_version 4 0
 
-if ! executable_exists 'appman'; then
-  die 'appman executable not found'
+if ! commands::executable_exists 'appman'; then
+  log::die 'appman executable not found'
 fi
 
-mapfile -t appimages_from_package_list < <(get_universal_packages 'appimage' "$@" | sort)
+mapfile -t appimages_from_package_list < <(packages::get_universal 'appimage' "$@" | sort)
 readonly appimages_from_package_list
 
 mapfile -t appimages_installed < <(find "${XDG_DATA_HOME}/appman/" -mindepth '1' -maxdepth '1' -type 'd' ! -name 'appman' -printf '%f\n' | sort)
 readonly appimages_installed
 
-mapfile -t appimages_to_install < <(comm -23 <(array_to_lines "${appimages_from_package_list[@]}") <(array_to_lines "${appimages_installed[@]}"))
+mapfile -t appimages_to_install < <(comm -23 <(arrays::to_lines "${appimages_from_package_list[@]}") <(arrays::to_lines "${appimages_installed[@]}"))
 readonly appimages_to_install
 
-mapfile -t appimages_to_remove < <(comm -13 <(array_to_lines "${appimages_from_package_list[@]}") <(array_to_lines "${appimages_installed[@]}"))
+mapfile -t appimages_to_remove < <(comm -13 <(arrays::to_lines "${appimages_from_package_list[@]}") <(arrays::to_lines "${appimages_installed[@]}"))
 readonly appimages_to_remove
 
-if (("${#appimages_to_install[@]}")) && prompt_yn 'Install missing AppImage packages?'; then
-  log 'Installing missing AppImage packages'
-  array_to_lines "${appimages_to_install[@]}" | xargs --no-run-if-empty appman install
-  log 'Installed missing AppImage packages'
+if (("${#appimages_to_install[@]}")) && prompt::yn 'Install missing AppImage packages?'; then
+  log::log 'Installing missing AppImage packages'
+  arrays::to_lines "${appimages_to_install[@]}" | xargs --no-run-if-empty appman install
+  log::log 'Installed missing AppImage packages'
 fi
 
 for appimage_to_remove in "${appimages_to_remove[@]}"; do
-  if prompt_yn "Remove ${appimage_to_remove}?"; then
-    log "Removing ${appimage_to_remove}"
+  if prompt::yn "Remove ${appimage_to_remove}?"; then
+    log::log "Removing ${appimage_to_remove}"
     # I don't know why remove operation exit code is non-zero
     appman -R "${appimage_to_remove}" || true
-    log "Removed ${appimage_to_remove}"
+    log::log "Removed ${appimage_to_remove}"
   fi
 done
 
-log 'Updating all AppImage packages'
+log::log 'Updating all AppImage packages'
 appman update
-log 'Updated all AppImage packages'
+log::log 'Updated all AppImage packages'
diff --git a/main/sync-flatpaks b/main/sync-flatpaks
--- a/main/sync-flatpaks
+++ b/main/sync-flatpaks
@@ -5,29 +5,29 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
+log::enable_err_trap
+system::require_bash_version 4 0
 
-if ! executable_exists 'flatpak'; then
-  die 'flatpak executable not found'
+if ! commands::executable_exists 'flatpak'; then
+  log::die 'flatpak executable not found'
 fi
 
-mapfile -t flatpaks_from_package_list < <(get_universal_packages 'flatpak' "$@" | sort)
+mapfile -t flatpaks_from_package_list < <(packages::get_universal 'flatpak' "$@" | sort)
 readonly flatpaks_from_package_list
 
 mapfile -t flatpaks_installed < <(flatpak list --user --app --columns application | sort)
 readonly flatpaks_installed
 
-mapfile -t flatpaks_to_install < <(comm -23 <(array_to_lines "${flatpaks_from_package_list[@]}") <(array_to_lines "${flatpaks_installed[@]}"))
+mapfile -t flatpaks_to_install < <(comm -23 <(arrays::to_lines "${flatpaks_from_package_list[@]}") <(arrays::to_lines "${flatpaks_installed[@]}"))
 readonly flatpaks_to_install
 
-mapfile -t flatpaks_to_remove < <(comm -13 <(array_to_lines "${flatpaks_from_package_list[@]}") <(array_to_lines "${flatpaks_installed[@]}"))
+mapfile -t flatpaks_to_remove < <(comm -13 <(arrays::to_lines "${flatpaks_from_package_list[@]}") <(arrays::to_lines "${flatpaks_installed[@]}"))
 readonly flatpaks_to_remove
 
-if (("${#flatpaks_to_install[@]}")) && prompt_yn 'Install missing Flatpak packages?'; then
-  log 'Installing missing Flatpak packages'
-  array_to_lines "${flatpaks_to_install[@]}" | xargs --no-run-if-empty flatpak install --user --noninteractive
-  log 'Installed missing Flatpak packages'
+if (("${#flatpaks_to_install[@]}")) && prompt::yn 'Install missing Flatpak packages?'; then
+  log::log 'Installing missing Flatpak packages'
+  arrays::to_lines "${flatpaks_to_install[@]}" | xargs --no-run-if-empty flatpak install --user --noninteractive
+  log::log 'Installed missing Flatpak packages'
 fi
 
 for flatpak_to_remove in "${flatpaks_to_remove[@]}"; do
@@ -35,21 +35,21 @@ for flatpak_to_remove in "${flatpaks_to_remove[@]}"; do
     flatpak list --user --app --columns name --columns application \
       | awk --field-separator $'\t' --assign "to_remove=${flatpak_to_remove}" '$2 == to_remove { print $1 }'
   )" || exit 1
-  if prompt_yn "Remove ${flatpak_name} (${flatpak_to_remove})?"; then
-    log "Removing ${flatpak_name} (${flatpak_to_remove})"
+  if prompt::yn "Remove ${flatpak_name} (${flatpak_to_remove})?"; then
+    log::log "Removing ${flatpak_name} (${flatpak_to_remove})"
     flatpak remove --user --noninteractive "${flatpak_to_remove}"
-    log "Removed ${flatpak_name} (${flatpak_to_remove})"
+    log::log "Removed ${flatpak_name} (${flatpak_to_remove})"
   fi
 done
 
-log 'Removing unused Flatpak runtimes'
+log::log 'Removing unused Flatpak runtimes'
 flatpak uninstall --user --noninteractive --unused
-log 'Removed unused Flatpak runtimes'
+log::log 'Removed unused Flatpak runtimes'
 
-log 'Updating all Flatpak packages'
+log::log 'Updating all Flatpak packages'
 flatpak update --user --noninteractive
-log 'Updated all Flatpak packages'
+log::log 'Updated all Flatpak packages'
 
-if flatpak list --user --app | contains_word_ignore_case 'com.google.chrome'; then
+if flatpak list --user --app | grep::contains_word_ignore_case 'com.google.chrome'; then
   flatpak override --user --filesystem="${HOME}/.local/share/applications:create" --filesystem="${HOME}/.local/share/icons:create" 'com.google.Chrome'
 fi
diff --git a/main/write-de-env-file b/main/write-de-env-file
--- a/main/write-de-env-file
+++ b/main/write-de-env-file
@@ -5,9 +5,9 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
 function eval_maven_expression() {
   mvn --file "${pom_file}" help:evaluate -Dexpression="$1" --quiet -DforceStdout
@@ -16,12 +16,12 @@ function eval_maven_expression() {
 readonly pom_file='pom.xml'
 readonly env_file='.env'
 
-if ! file_exists "${pom_file}"; then
-  die "${pom_file} is missing"
+if ! files::exists "${pom_file}"; then
+  log::die "${pom_file} is missing"
 fi
 
-if file_exists "${env_file}"; then
-  die "${env_file} exists"
+if files::exists "${env_file}"; then
+  log::die "${env_file} exists"
 fi
 
 artifact_id="$(eval_maven_expression 'project.artifactId')"
diff --git a/set_up/dnf/add-dnf-rpmfusion-repos b/set_up/dnf/add-dnf-rpmfusion-repos
--- a/set_up/dnf/add-dnf-rpmfusion-repos
+++ b/set_up/dnf/add-dnf-rpmfusion-repos
@@ -5,25 +5,25 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
-if ! is_fedora; then
+if ! os::is_fedora; then
   exit 0
 fi
 
-if ! executable_exists 'dnf'; then
-  log 'dnf executable not found'
+if ! commands::executable_exists 'dnf'; then
+  log::log 'dnf executable not found'
   exit 0
 fi
 
-if ! prompt_yn 'Add RPM Fusion repos?'; then
+if ! prompt::yn 'Add RPM Fusion repos?'; then
   exit 0
 fi
 
 for repo in 'rpmfusion-free-release' 'rpmfusion-nonfree-release'; do
-  if ! dnf list --installed "${repo}" > '/dev/null' 2>&1 && prompt_yn "Add ${repo} repository?"; then
+  if ! dnf list --installed "${repo}" > '/dev/null' 2>&1 && prompt::yn "Add ${repo} repository?"; then
     if [[ "${repo}" == 'rpmfusion-free-release' ]]; then
       sudo dnf install "https://mirrors.rpmfusion.org/free/fedora/${repo}-$(rpm --eval='%fedora').noarch.rpm"
     else
diff --git a/set_up/dnf/copy-dnf-conf-file b/set_up/dnf/copy-dnf-conf-file
--- a/set_up/dnf/copy-dnf-conf-file
+++ b/set_up/dnf/copy-dnf-conf-file
@@ -5,18 +5,18 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
-if ! is_fedora; then
+if ! os::is_fedora; then
   exit 0
 fi
-if ! executable_exists 'dnf'; then
-  log 'dnf executable not found'
+if ! commands::executable_exists 'dnf'; then
+  log::log 'dnf executable not found'
   exit 0
 fi
 
 readonly src_file="${HOME}/.etc/dnf.conf"
 readonly dest_file='/etc/dnf/dnf.conf'
-root_copy_file "${src_file}" "${dest_file}"
+files::root_copy "${src_file}" "${dest_file}"
diff --git a/set_up/grub/remove-quiet-splash-and-rhgb b/set_up/grub/remove-quiet-splash-and-rhgb
--- a/set_up/grub/remove-quiet-splash-and-rhgb
+++ b/set_up/grub/remove-quiet-splash-and-rhgb
@@ -5,34 +5,34 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
-if ! is_server; then
+if ! hosts::is_server; then
   exit 0
 fi
 
-if ! executable_exists 'grub-mkconfig' && ! executable_exists 'grub2-mkconfig'; then
+if ! commands::executable_exists 'grub-mkconfig' && ! commands::executable_exists 'grub2-mkconfig'; then
   exit 0
 fi
 
 # These pairing of commands and GRUB output config file may not always be
 # correct, but seems to be consistent with the distros I've looked at recently.
-if executable_exists 'grub-mkconfig'; then
+if commands::executable_exists 'grub-mkconfig'; then
   readonly grub_mkconfig_cmd='grub-mkconfig'
   readonly grub_config_file='/boot/grub/grub.cfg'
 else
   readonly grub_mkconfig_cmd='grub2-mkconfig'
   readonly grub_config_file='/boot/grub2/grub.cfg'
 fi
-if ! file_exists "${grub_config_file}"; then
-  die "Could not find GRUB config file at: ${grub_config_file}"
+if ! files::exists "${grub_config_file}"; then
+  log::die "Could not find GRUB config file at: ${grub_config_file}"
 fi
 
 readonly grub_default_file='/etc/default/grub'
-if ! file_exists "${grub_default_file}"; then
-  die "Unable to find file: ${grub_default_file}"
+if ! files::exists "${grub_default_file}"; then
+  log::die "Unable to find file: ${grub_default_file}"
 fi
 
 readonly kernel_options_to_remove=(
@@ -43,10 +43,10 @@ readonly kernel_options_to_remove=(
 
 contains_options_to_remove='n'
 while read -r line; do
-  if contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX_DEFAULT|GRUB_CMDLINE_LINUX)\s*=' <<< "${line}"; then
+  if grep::contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX_DEFAULT|GRUB_CMDLINE_LINUX)\s*=' <<< "${line}"; then
     options="$(cut --delimiter='"' --fields=2 <<< "${line}")" || exit 1
     for kernel_option in "${kernel_options_to_remove[@]}"; do
-      if printf '%s\n' "${options}" | contains_word "${kernel_option}"; then
+      if printf '%s\n' "${options}" | grep::contains_word "${kernel_option}"; then
         contains_options_to_remove='y'
         break
       fi
@@ -61,7 +61,7 @@ if [[ "${contains_options_to_remove}" == 'n' ]]; then
   exit 0
 fi
 readonly kernel_options_to_remove_string="${kernel_options_to_remove[*]}"
-if ! prompt_yn "Remove GRUB kernel options: ${kernel_options_to_remove_string// /, }"; then
+if ! prompt::yn "Remove GRUB kernel options: ${kernel_options_to_remove_string// /, }"; then
   exit 0
 fi
 
@@ -69,14 +69,14 @@ sudo cp "${grub_default_file}" "${grub_default_file}.orig"
 sudo truncate --size=0 "${grub_default_file}"
 while read -r line; do
   line_to_write="${line}"
-  if contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX)|(GRUB_CMDLINE_LINUX_DEFAULT)\s*=' <<< "${line}"; then
+  if grep::contains_perl_regex '^\s*(GRUB_CMDLINE_LINUX)|(GRUB_CMDLINE_LINUX_DEFAULT)\s*=' <<< "${line}"; then
     for kernel_option in "${kernel_options_to_remove[@]}"; do
       #shellcheck disable=SC2001
       line_to_write="$(sed "s/${kernel_option}//g" <<< "${line_to_write}")" || exit 1
     done
     line_to_write="$(sed 's/\s*"\s*/"/g ; s/\s\+/ /g' <<< "${line_to_write}")" || exit 1
   fi
-  root_append_to_file "${grub_default_file}" "${line_to_write}"
+  files::root_append_to "${grub_default_file}" "${line_to_write}"
 done < "${grub_default_file}.orig"
 
 sudo "${grub_mkconfig_cmd}" --output="${grub_config_file}"
diff --git a/set_up/pacman/copy-pacman-hooks b/set_up/pacman/copy-pacman-hooks
--- a/set_up/pacman/copy-pacman-hooks
+++ b/set_up/pacman/copy-pacman-hooks
@@ -5,20 +5,20 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
-if ! is_arch && ! is_cachyos; then
+if ! os::is_arch && ! os::is_cachyos; then
   exit 0
 fi
-if ! executable_exists 'pacman'; then
-  log 'pacman executable not found'
+if ! commands::executable_exists 'pacman'; then
+  log::log 'pacman executable not found'
   exit 0
 fi
 
 readonly hooks_dir="/etc/pacman.d/hooks"
 for hook_file in "${HOME}/.etc/pacman-"*".hook"; do
   hook_file_name="$(basename "${hook_file}")" || exit 1
-  root_copy_file "${hook_file}" "${hooks_dir}/${hook_file_name:7}"
+  files::root_copy "${hook_file}" "${hooks_dir}/${hook_file_name:7}"
 done
diff --git a/set_up/ufw/configure-ufw b/set_up/ufw/configure-ufw
--- a/set_up/ufw/configure-ufw
+++ b/set_up/ufw/configure-ufw
@@ -5,47 +5,47 @@ IFS=$'\n\t'
 
 #shellcheck disable=SC1091
 source "${SCRIPTS_DIR}/functions.bash"
-enable_err_trap
-require_bash_version 4 0
-check_no_args "$@"
+log::enable_err_trap
+system::require_bash_version 4 0
+args::check_no_args "$@"
 
-if ! executable_exists 'ufw'; then
-  log 'ufw executable not found'
+if ! commands::executable_exists 'ufw'; then
+  log::log 'ufw executable not found'
   exit 0
 fi
 
-if ! sudo ufw status verbose | contains_word_ignore_case 'deny (incoming)'; then
-  if prompt_yn 'Set UFW to deny incoming?'; then
+if ! sudo ufw status verbose | grep::contains_word_ignore_case 'deny (incoming)'; then
+  if prompt::yn 'Set UFW to deny incoming?'; then
     sudo ufw default deny 'incoming'
   fi
 fi
 
-if ! sudo ufw status verbose | contains_perl_regex_ignore_case 'anywhere on tailscale0\s+allow in\s+anywhere'; then
-  if prompt_yn 'Set UFW to allow incoming traffic from tailnet?'; then
+if ! sudo ufw status verbose | grep::contains_perl_regex_ignore_case 'anywhere on tailscale0\s+allow in\s+anywhere'; then
+  if prompt::yn 'Set UFW to allow incoming traffic from tailnet?'; then
     sudo ufw allow in on 'tailscale0'
   fi
 fi
 
-if ! sudo ufw status verbose | contains_perl_regex_ignore_case '22/tcp\s+allow in\s+anywhere'; then
-  if prompt_yn 'Set UFW to allow incoming traffic on port 22 (ssh)?'; then
+if ! sudo ufw status verbose | grep::contains_perl_regex_ignore_case '22/tcp\s+allow in\s+anywhere'; then
+  if prompt::yn 'Set UFW to allow incoming traffic on port 22 (ssh)?'; then
     sudo ufw allow ssh
   fi
 fi
 
-if is_server && ! sudo ufw status verbose | contains_perl_regex_ignore_case '45876/tcp\s+allow in\s+169\.254\.0\.0/16'; then
-  if prompt_ny 'Set UFW to allow incoming traffic on port 45876 (beszel) from 169.254.0.0/16 (docker IP range)?'; then
+if hosts::is_server && ! sudo ufw status verbose | grep::contains_perl_regex_ignore_case '45876/tcp\s+allow in\s+169\.254\.0\.0/16'; then
+  if prompt::ny 'Set UFW to allow incoming traffic on port 45876 (beszel) from 169.254.0.0/16 (docker IP range)?'; then
     sudo ufw allow from '169.254.0.0/16' to any port '45876' proto 'tcp'
   fi
 fi
 
-if ! sudo ufw status verbose | contains_word_ignore_case 'allow (outgoing)'; then
-  if prompt_yn 'Set UFW to allow outgoing?'; then
+if ! sudo ufw status verbose | grep::contains_word_ignore_case 'allow (outgoing)'; then
+  if prompt::yn 'Set UFW to allow outgoing?'; then
     sudo ufw default allow 'outgoing'
   fi
 fi
 
-if ! sudo ufw status verbose | contains_word_ignore_case 'status: active'; then
-  if prompt_yn 'Enable UFW?'; then
+if ! sudo ufw status verbose | grep::contains_word_ignore_case 'status: active'; then
+  if prompt::yn 'Enable UFW?'; then
     sudo ufw --force enable
   fi
 fi
