misc stuff before reworking

diff --git a/arch/arch_setup b/arch/arch_setup
--- a/arch/arch_setup
+++ b/arch/arch_setup
@@ -1,10 +1,21 @@
 #!/usr/bin/env bash
 
-set -euox pipefail
+set -euo pipefail
+
+export XDG_DATA_HOME="${HOME}/.local/share"
+export XDG_CONFIG_HOME="${HOME}/.config"
+export XDG_STATE_HOME="${HOME}/.local/state"
+export XDG_CACHE_HOME="${HOME}/.cache"
 
 function prompt() {
-  read -rp "$1 [Y/n]"
-  if [[ "${REPLY}" == '' || "${REPLY}" == [yY] ]]; then
+  read -rp "$1: "
+  echo "${REPLY}"
+}
+
+function prompt_yn() {
+  local yn_reply
+  yn_reply="$(prompt "$1 [Y/n]")"
+  if [[ "${yn_reply}" == '' || "${yn_reply}" == [yY] ]]; then
     echo 'y'
   else
     echo 'n'
@@ -12,169 +23,188 @@ function prompt() {
 }
 
 function prompt_packages() {
-  prompt "Install $1 packages?"
+  prompt_yn "Install $1 packages?"
 }
 
 function log() {
-  echo ">>> $1" >&2
+  echo "arch_setup: $1"
 }
 
-function do_install_aur_helper() {
-  if [[ "$1" == 'y' ]]; then
-    log "Installing $2"
-    return
-  else
-    log "Skipping installing $2"
-  fi
-  false
+function executable_exists() {
+  type -aPf "$1" > /dev/null 2>&1
 }
 
-function install_aur_helper() {
-  sudo pacman --sync --needed 'base-devel' 'git'
-  readonly tmp_dir="$(mktemp --directory)"
-  cd "${tmp_dir}"
-  git clone "https://aur.archlinux.org/$1.git"
-  cd "$1"
-  makepkg -si
+function get_package_list() {
+  curl "https://raw.githubusercontent.com/rvenutolo/Scripts/main/arch/packages/$1.txt"
 }
 
-function do_install_packages() {
-  if [[ "$1" == 'y' ]]; then
-    log "Installing $2 packages"
-    return
-  else
-    log "Skipping installing $2 packages"
-  fi
-  false
+function install_package() {
+  yay --sync --needed --noconfirm "$1"
 }
 
-function get_package_file_url() {
-  echo "https://raw.githubusercontent.com/rvenutolo/Scripts/main/arch/packages/$1/$2.txt"
+function install_packages() {
+  ## TODO install packages one-by-one and capture those that fail
+  # shellcheck disable=SC2046
+  yay --sync --needed --noconfirm --batchinstall $(get_package_list "$1")
 }
 
-function pacman_install() {
-  curl "$(get_package_file_url "$1" "$2")" | sudo pacman --sync --needed --noconfirm -
-}
-
-function aur_install() {
-  if [[ "${install_paru}" == 'y' ]]; then
-    curl "$(get_package_file_url "$1" "$2")" | paru --aur --sync --needed --noconfirm -
-  elif [[ "${install_yay}" == 'y' ]]; then
-    curl "$(get_package_file_url "$1" "$2")" | yay --aur --sync --needed --noconfirm -
-  else
-    echo "Neither paru or yay is installed. Skipping installing AUR packages."
-    exit 2
-  fi
-}
-
-readonly use_reflector="$(prompt 'Use reflector to update mirrors and choose fastest?')"
-readonly add_chaotic_aur="$(prompt 'Enable Chaotic AUR?')"
-readonly install_paru="$(prompt 'Install paru?')"
-readonly install_yay="$(prompt 'Install yay?')"
-readonly install_aws_cli="$(prompt 'Install AWS CLI?')"
-
-readonly install_native_cli="$(prompt_packages 'native CLI')"
-readonly install_personal_native_cli="$(prompt_packages 'personal native CLI')"
-readonly install_native_gui="$(prompt_packages 'native GUI')"
-readonly install_personal_native_gui="$(prompt_packages 'personal native GUI')"
-readonly install_aur_cli="$(prompt_packages 'AUR CLI')"
-readonly install_personal_aur_cli="$(prompt_packages 'personal AUR CLI')"
-readonly install_aur_gui="$(prompt_packages 'AUR GUI')"
-readonly install_personal_aur_gui="$(prompt_packages 'personal AUR GUI')"
+readonly init_chezmoi="$(prompt_yn 'Initialize chezmoi?')"
+readonly install_cli="$(prompt_packages 'CLI')"
+readonly install_personal_cli="$(prompt_packages 'personal CLI')"
+readonly install_gui="$(prompt_packages 'GUI')"
+readonly install_personal_gui="$(prompt_packages 'personal GUI')"
 readonly install_flatpak_packages="$(prompt_packages 'Flatpak')"
-readonly install_sdkman_packages="$(prompt_packages 'SDKMAN')"
+readonly install_aws_cli="$(prompt_yn 'Install AWS CLI?')"
+readonly setup_reflector="$(prompt_yn 'Setup reflector service?')"
+readonly setup_autotrash="$(prompt_yn 'Setup autotrash service?')"
+readonly setup_journalctl_vacuum="$(prompt_yn 'Setup journalctl vacuum service?')"
+readonly setup_ssh_agent="$(prompt_yn 'Setup ssh-agent service?')"
 
-log 'Updating existing packages'
-sudo pacman --sync --refresh --sysupgrade
-
-if [[ "${use_reflector}" == 'y' ]]; then
-  log 'Updating mirrors and choosing fastest'
-  sudo pacman --sync --needed --noconfirm 'reflector'
-  sudo reflector --country 'United States' --age '12' --protocol 'https' --sort 'rate' --save '/etc/pacman.d/mirrorlist'
-else
-  log 'Skipping updating mirrors and choosing fastest'
+if ! localectl | grep --quiet --fixed-strings 'LANG=en_US.UTF-8'; then
+  if ! grep --quiet '^en_US.UTF-8 UTF-8' '/etc/locale.gen'; then
+      echo 'en_US.UTF-8 UTF-8' | sudo tee -a '/etc/locale.gen' > /dev/null
+    fi
+    sudo locale-gen
+    sudo localectl set-locale 'LANG=en_US.UTF-8'
+    unset LANG
+    set +u
+    source '/etc/profile.d/locale.sh'
+    set -u
 fi
 
-if [[ "${add_chaotic_aur}" == 'y' ]]; then
+if ! grep --quiet '^\[multilib]' '/etc/pacman.conf'; then
+  log 'Enabling multilib repository'
+  echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a '/etc/pacman.conf' > /dev/null
+fi
+
+if ! grep --quiet '^\[chaotic-aur]' '/etc/pacman.conf'; then
   log 'Adding Chaotic AUR'
   sudo pacman-key --recv-key 'FBA220DFC880C036' --keyserver 'keyserver.ubuntu.com'
   sudo pacman-key --lsign-key 'FBA220DFC880C036'
   sudo pacman --upgrade --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
-  echo "
-  [chaotic-aur]
-  Include = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf
-  sudo pacman --sync --refresh --sysupgrade
-else
-  log 'Skipping adding Chaotic AUR'
+  echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a '/etc/pacman.conf' > /dev/null
 fi
 
-if do_install_aur_helper "${install_paru}" 'paru'; then
-  install_aur_helper 'paru'
+# yay & paru should be in Chaotic AUR and thus installable via pacman
+sudo pacman --sync --refresh --sysupgrade --noconfirm --needed 'base-devel' 'reflector' 'yay' 'paru' 'chezmoi' 'nano' 'git' 'age'
+
+if [[ "${init_chezmoi}" == 'y' ]]; then
+  log 'Initializing chezmoi'
+  readonly chezmoi_dotfiles_dir="${HOME}/Code/chezmoi-dotfiles"
+  chezmoi init --apply --source "${chezmoi_dotfiles_dir}" 'https://github.com/rvenutolo/chezmoi-dotfiles.git'
+  git --git-dir "${chezmoi_dotfiles_dir}/.git" remote set-url 'origin' 'git@github.com:rvenutolo/chezmoi-dotfiles.git'
+else
+  log 'Skipping initializing chezmoi'
 fi
-if do_install_aur_helper "${install_yay}" 'yay'; then
-  install_aur_helper 'yay'
+
+set +u
+# source this to get non-default paths, like 'export STACK_ROOT="${XDG_DATA_HOME}/stack"'
+if [[ -f "${XDG_CONFIG_HOME}/bash/exports" ]]; then
+  source "${XDG_CONFIG_HOME}/bash/exports"
+fi
+set -u
+
+## TODO figure out what needs python2
+install_package 'python2-bin'
+
+if [[ "${install_cli}" == 'y' ]]; then
+  log 'Installing CLI packages'
+  install_packages 'cli'
+else
+  log 'Skipping installing CLI packages'
+fi
+
+if [[ "${install_personal_cli}" == 'y' ]]; then
+  log 'Installing personal CLI packages'
+  install_packages 'cli_personal'
+else
+  log 'Skipping installing personal CLI packages'
+fi
+
+if [[ "${install_gui}" == 'y' ]]; then
+  log 'Installing GUI packages'
+  install_packages 'gui'
+else
+  log 'Skipping installing GUI packages'
+fi
+
+if [[ "${install_personal_gui}" == 'y' ]]; then
+  log 'Installing personal GUI packages'
+  install_packages 'gui_personal'
+else
+  log 'Skipping installing personal GUI packages'
+fi
+
+if [[ "${install_flatpak_packages}" == 'y' ]]; then
+  log 'Installing flatpaks'
+  install_package 'flatpak'
+  flatpak remote-add --if-not-exists 'flathub' 'https://flathub.org/repo/flathub.flatpakrepo'
+  # shellcheck disable=SC2046
+  flatpak install --noninteractive flathub $(get_package_list 'flatpaks' | tr '\n' ' ')
+else
+  log 'Skipping installing flatpaks'
 fi
 
 if [[ "${install_aws_cli}" == 'y' ]]; then
   log 'Installing AWS CLI'
+  install_package 'unzip'
   readonly aws_cli_url='https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
   readonly aws_cli_tmp_dir="$(mktemp --directory)"
   readonly aws_cli_zip_file="${aws_cli_tmp_dir}/aws_cli.zip"
-  curl --silent --location --output "${aws_cli_zip_file}" "${aws_cli_url}"
+  curl --silent --output "${aws_cli_zip_file}" "${aws_cli_url}"
   unzip -q "${aws_cli_zip_file}" -d "${aws_cli_tmp_dir}"
   sudo "${aws_cli_tmp_dir}/aws/install" --bin-dir '/usr/local/bin' --install-dir '/usr/local/aws-cli' --update
 else
   log 'Skipping installing AWS CLI'
 fi
 
-if do_install_packages "${install_native_cli}" 'native CLI'; then
-  pacman_install 'native' 'cli'
-fi
-if do_install_packages "${install_personal_native_cli}" 'personal native CLI'; then
-  pacman_install 'native' 'cli_personal'
-fi
-if do_install_packages "${install_native_gui}" 'native GUI'; then
-  pacman_install 'native' 'gui'
-fi
-if do_install_packages "${install_personal_native_gui}" 'personal native GUI'; then
-  pacman_install 'native' 'gui_personal'
-fi
-if do_install_packages "${install_aur_cli}" 'AUR CLI'; then
-  aur_install 'aur' 'cli'
-fi
-if do_install_packages "${install_personal_aur_cli}" 'personal AUR CLI'; then
-  aur_install 'aur' 'cli_personal'
-fi
-if do_install_packages "${install_aur_gui}" 'AUR GUI'; then
-  aur_install 'aur' 'gui'
-fi
-if do_install_packages "${install_personal_aur_gui}" 'personal AUR GUI'; then
-  aur_install 'aur' 'gui_personal'
+#if [[ "${setup_reflector}" == 'y' ]]; then
+#  log 'Setting up reflector service'
+#  sudo sed -i '/^$/q' '/etc/xdg/reflector/reflector.conf'
+#  echo -e '--country United States\n--age 12\n--protocol https\n--sort rate\n--save /etc/pacman.d/mirrorlist' | sudo tee -a '/etc/xdg/reflector/reflector.conf' > /dev/null
+#  sudo systemctl enable 'reflector.timer'
+#else
+#  log 'Skipping setting up reflector service'
+#fi
+#
+#if [[ "${setup_autotrash}" == 'y' ]]; then
+#  log 'Setting up autotrash service'
+#  if executable_exists 'autotrash'; then
+#    if [[ -f "${XDG_CONFIG_HOME}/systemd/user/autotrash.timer" ]]; then
+#      systemctl --user enable 'autotrash.timer'
+#    else
+#      log 'autotrash.timer not found - Skipping setting up autotrash service'
+#    fi
+#  else
+#    log 'autotrash not found - Skipping setting up autotrash service'
+#  fi
+#else
+#  log 'Skipping setting up autotrash service'
+#fi
+#
+#if [[ "${setup_journalctl_vacuum}" == 'y' ]]; then
+#  log 'Setting up journalctl vacuum service'
+#  if [[ -f "${XDG_CONFIG_HOME}/systemd/user/journalctl-vacuum.timer" ]]; then
+#    systemctl --user enable 'journalctl-vacuum.timer'
+#  else
+#    log 'journalctl-vacuum.timer not found - Skipping setting up journalctl vacuum service'
+#  fi
+#else
+#  log 'Skipping setting up journalctl vacuum service'
+#fi
+
+
+if [[ -f "${HOME}/.bash_logout" ]]; then
+  rm "${HOME}/.bash_logout"
 fi
 
-if do_install_packages "${install_flatpak_packages}" 'Flatpak'; then
-  curl "$(get_package_file_url 'flatpak' 'flatpaks')" | flatpak install flathub -
-fi
+## TODO dnous
 
-if do_install_packages "${install_sdkman_packages}" 'SDKMAN'; then
-  export SDKMAN_DIR="$HOME/.local/share/sdkman"
-  curl --silent 'https://get.sdkman.io' | bash
-  source "${SDKMAN_DIR}/bin/sdkman-init.sh"
-  sdk install gradle
-  sdk install groovy
-  sdk install java
-  sdk install kotlin
-  sdk install maven
-  sdk install mcs
-  sdk install micronaut
-  sdk install mvnd
-  sdk install pomchecker
-  sdk install sbt
-  sdk install scala
-  sdk install skeletal
-  sdk install spark-submit
-  sdk install spring
-  sdk install visualvm
-fi
+## TODO chezmoi
 
-# TODO parquet-tools ptop riff tabs2spaces flatseal eyeD3
+# TODO trash-d parquet-tools ptop riff tabs2spaces flatseal eyeD3
+
+## TODO tageditor-cli
+## TODO maldet needs lib32-glibc
+## TODO trash-d install fails
+## TODO something about parquet-tools
